config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :flights
root 'welcome#index'

end

app/models/flight.rb
class Flight < ActiveRecord::Base

	CITY_OPTION = ["SGP", "SZX", "HKG", "JFK", "BOS", "SEA"]
	#before_save {departuredate <= arrivedate}

	validates_inclusion_of :from, :in => CITY_OPTION, :message => "Airport you input should only be one of SGP, SZX, HKG, JFK, BOS, SEA"
	validates_inclusion_of :to, :in => CITY_OPTION, :message => "Airport you input should only be one of SGP, SZX, HKG, JFK, BOS, SEA"
	
	validates_time :start_time
	validates_time :flying_time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

 def index
	@flights= Flight.all
	@flight = Flight.new
end

def new
	redirect_to flights_path
end

def create

	@flights= Flight.all
	@flight = Flight.new(flight_params)
 
	if @flight.save
		redirect_to flights_path
	else
		render 'index'
	end
end

def update

	  @flights= Flight.all
	  @flight = Flight.find(params[:id])
 
	  if @flight.update(flight_params)
		redirect_to flights_path
	  else
		redirect_to flights_path
	  end


end

def destroy

  @flight = Flight.find(params[:id])
  @flight.destroy
 
  redirect_to flights_path
end


private
  def flight_params
    params.require(:flight).permit(:from, :to, :start_time, :flying_time, :carrier_name, :flight_model)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/flights/index.html.erb
<h1>www.airlines-list.com</h1>
<style type="text/css">
@import url("../style.css")
</style>
<table>
  <tr>
    <th>From Airport</th>
    <th>To Airport</th>
	<th>Start Time</th>
	<th>Flying Time</th>
	<th>Carrier Name</th>
	<th>Flight Model</th>
  </tr>
		
	<% @flights.each do |flight| %>
		<tr>
			<%= form_for :flight, url: flight_path(flight), method: :patch do |f| %>
					<td><%= f.text_field :from, :value => flight.from %></td>
					<td><%= f.text_field :to, :value => flight.to %></td>
					<td><%= f.text_field :start_time, :value => flight.start_time.strftime("%H:%M") %></td>
					<td><%= f.text_field :flying_time, :value => flight.flying_time.strftime("%H:%M") %></td>
					<td><%= f.text_field :carrier_name, :value => flight.carrier_name %></td>
					<td><%= f.text_field :flight_model, :value => flight.flight_model %></td>
					<td><%= f.submit :value =>'Save'%></td>
					<td><%= link_to '<button type="button">Delete</button>'.html_safe, flight_path(flight), method: :delete %></td>
			<%end%>
		</tr>
	<% end %>

	<%= form_for :flight, url: flights_path  do |f| %>
		<tr>
			<td><%= f.text_field :from %></td>
			<td><%= f.text_field :to %></td>
			<td><%= f.time_select :start_time, :selected => Time.now %></td>
			<td><%= f.time_select :flying_time %></td>
			<td><%= f.text_field :carrier_name %></td>
			<td><%= f.text_field :flight_model %></td>
			<td><%= f.submit :value =>"Add"%></td>
		</tr>
	<% end %>
</table>

<table>		
	<tr>
		<td>
			<% if @flight.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>
					<ul>
						<% @flight.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
		</td>
	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Welend</title>
	<%= javascript_include_tag :defaults %>
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Thanks</h1>